// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of TodoMarkDone.
  nonisolated static let TodoMarkDonePayload = ApolloAPI.Object(
    typename: "TodoMarkDonePayload",
    implementedInterfaces: [],
    keyFields: nil
  )
}