query Project($fullPath: ID!) {
  project(fullPath: $fullPath) {
    id
    avatarUrl
    name
    visibility
    description
    topics
    starCount
    forksCount
    issuesEnabled
    openIssuesCount
    mergeRequestsEnabled
    wikiEnabled
    jobsEnabled
    openMergeRequestsCount
    webUrl
    httpUrlToRepo
    sshUrlToRepo
    createdAt
    archived
    namespace {
      id
      name
      fullPath
    }
    statistics {
      commitCount
      repositorySize
    }
    releases {
      count
    }
    labels {
      count
    }
    repository {
      rootRef
      readme: blobs(paths: ["README.md", "README", "README.txt"], first: 1) {
        nodes {
          rawTextBlob
        }
      }
      license: blobs(paths: ["LICENSE", "LICENSE.txt", "LICENSE.md", "COPYING"], first: 1) {
        nodes {
          rawTextBlob
        }
      }
      contributing: blobs(paths: ["CONTRIBUTING", "CONTRIBUTING.txt", "CONTRIBUTING.md"], first: 1) {
        nodes {
          rawTextBlob
        }
      }
      tree {
        lastCommit {
          id
          title
          shortId
          authorName
          authoredDate
          webUrl
          signature {
            verificationStatus
          }
          pipelines {
            nodes {
              status
            }
          }
        }
      }
    }
    languages {
      name
      share
      color
    }
    userPermissions {
      createIssue
      forkProject
      requestAccess
    }
  }
}
